Add flows dynamically
s8sg/goflow pull request #74
Opened 2023-06-27 10:02 UTC by dan2li

[Feature] Support dynamically appending flows after the flow service started.

**Code Change:**
* Add interface `AppendFlows()`  to `FlowService` and `FlowRuntime`.
* Initialize queues for appended flows.

2023-06-27 12:12 UTC, s8sg commented
Hey Dan, Lets create an issue first. We can discuss first and decide on the
approach and necessity.

On Tue, 27 Jun 2023 at 17:02, dan ***@***.***> wrote:

> [Feature] Support dynamically appending flows after the flow service
> started.
>
> *Code Change:*
>
>    - Add interface AppendFlows() to FlowService and FlowRuntime.
>    - Initialize queues for appended flows.
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/s8sg/goflow/pull/74
> Commit Summary
>
>    - 5789044
>    <https://github.com/s8sg/goflow/pull/74/commits/57890445495d7105240bb8507fc0b9ef513034eb>
>    register workflows dynamically.
>    - 7930e2c
>    <https://github.com/s8sg/goflow/pull/74/commits/7930e2caa167868b45ef2a9ae2f3b07aa7b2f66f>
>    AppendFlows can only be called after the flow service started
>    - c97b55b
>    <https://github.com/s8sg/goflow/pull/74/commits/c97b55b5ba7d705240bbdea021f4d1963d297dad>
>    create redis connection with OpenConnectionV2
>
> File Changes
>
> (2 files <https://github.com/s8sg/goflow/pull/74/files>)
>
>    - *M* runtime/flow_runtime.go
>    <https://github.com/s8sg/goflow/pull/74/files#diff-2c669f9eb6dc8bba344ac81c5e311195b1baeb042bd0f51e8c68ce47c3be10d7>
>    (157)
>    - *M* v1/goflow.go
>    <https://github.com/s8sg/goflow/pull/74/files#diff-cd94de89fab8a3436e54df19ad011561e8eed8979bc586e0ee625a918e361963>
>    (14)
>
> Patch Links:
>
>    - https://github.com/s8sg/goflow/pull/74.patch
>    - https://github.com/s8sg/goflow/pull/74.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/s8sg/goflow/pull/74>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABYIJ2QNBDTCRBIVHNUOHPDXNKVU5ANCNFSM6AAAAAAZVLMHYU>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-06-27 13:58 UTC, dan2li commented
@s8sg  Here, https://github.com/s8sg/goflow/issues/75

2023-07-08 03:42 UTC, s8sg requested changes
I’ll suggest to update the register to do both. It will handle both when queue worker has started and we want to append

2023-07-11 06:51 UTC, dan2li commented
@s8sg 
New commit to enable `Register()` to support dynamically registering flow.
Changes:
1.  Add `Register` method to the `FlowRuntime` to support dynamically registering flow.
2. Add `EnterWorkerMode` and `ExitWorkerMode` methods to the `FlowRuntime` to enable entering and exiting worker mode.
3. Remove `runtime.StartQueueWorker`, as it is no longer needed to create task queues for each flow at startup.

2023-07-14 14:40 UTC, s8sg approved these changes

2023-07-14 14:44 UTC, s8sg commented on v1/goflow.go
> +	if err := fs.setWorkerMode(false); err != nil {
This will block ?

2023-07-16 02:13 UTC, merged

2023-07-16 02:42 UTC, s8sg commented
@dan2li I faced some issue with the MR 
Created a new MR: https://github.com/s8sg/goflow/pull/79
We can discuss and work on the changes there 
Once everything looks good you can create a new MR. 
WDYT ?

2023-07-16 02:44 UTC, s8sg commented
Also lets add some overview of the changes in terms on 
* How its impact the responsibility of functions 
* If possible add  a flowchart of the code